"""所有常量"""
import pygame

# 水平方向上窗口尺寸的比例
SCALE_VERTICAL = 4 / 5
# 垂直方向上窗口尺寸的比例
SCALE_HORIZONTAL = 2 / 5
# 动画的最大帧率
MAX_FRAMERATE = 30

# 创建子弹事件id
ID_OF_CREATE_BULLET = pygame.USEREVENT
ID_OF_CREATE_DOUBLE_BULLET = pygame.USEREVENT + 7
# 创建小型敌机事件id
ID_OF_CREATE_SMALL_ENEMY = pygame.USEREVENT + 1
# 创建小型敌机事件id
ID_OF_CREATE_MID_ENEMY = pygame.USEREVENT + 2
# 创建小型敌机事件id
ID_OF_CREATE_BIG_ENEMY = pygame.USEREVENT + 3
# 解除我方飞机无敌状态事件
ID_OF_CANCLE_INVINCIBLE = pygame.USEREVENT + 4
# 去掉无敌护盾事件
ID_OF_CANCLE_INVINCIBLE_CIRCLE_SPEED = pygame.USEREVENT + 5
ID_OF_CREATE_BULLET_SUPPLY = pygame.USEREVENT + 6

# 创建子弹时间间隔
INTERVAL_OF_CREATE_BULLET = 200
INTERVAL_OF_CREATE_DOUBLE_BULLET = 200
INTERVAL_OF_CREATE_SMALL_ENEMY = 2000
INTERVAL_OF_CREATE_MID_ENEMY = 3600
INTERVAL_OF_CREATE_BIG_ENEMY = 18000
INTERVAL_OF_CANCLE_INVINCIBLE = 5000
# 无敌护盾递减事件间隔
INTERVAL_OF_INVINCIBLE_CIRCLE_SPEED = 100
INTERVAL_OF_CREATE_BULLET_SUPPLY = 8000
INTERVAL_OF_CREATE_BOMB_SUPPLY = 2000

# 爆炸音量
EXPLODE_SOUND_VOLUME = 0.8
BG_SOUND_VOLUME = 0.3

# 切换我方飞机图片的频率
MY_PLANE_SWITCH_IMAGE_FREQUENCY = 3
# 大型敌机图片切换评率
MID_ENEMY_SWITCH_IMAGE_FREQUENCY = 3
# 小型敌机爆炸切换图片评率
SMALL_ENEMY_SWITCH_EXPLODE_IMAGE_FREQUENCY = 4
# 中型敌机爆炸切换图片评率
MID_ENEMY_SWITCH_EXPLODE_IMAGE_FREQUENCY = 4
# 大型敌机爆炸切换图片评率
BIG_ENEMY_SWITCH_EXPLODE_IMAGE_FREQUENCY = 6
# 中型敌机击中切换图片评率
MID_ENEMY_SWITCH_HIT_IMAGE_FREQUENCY = 2
# 大型敌机击中切换图片评率
BIG_ENEMY_SWITCH_HIT_IMAGE_FREQUENCY = 2

# 敌机能量
MID_ENERGY = 5
BIG_ENERGY = 10

# 炸弹初始数量
BOMB_INITIAL_NUMBER = 3
# 我方飞机初始生命数
LIFE_NUM = 4
# 间距
MARGIN = 10
# 无敌护盾宽度
INVINCIBLE_CIRCLE_WIDTH = 10
# 无敌护盾颜色
INVINCIBLE_CIRCLE_COLOR = (254, 207, 57)

# 字体大小
FONT_SIZE = 36
WHITE_COLOR = (255, 255, 255)

# 双发子弹计数器
DOUBLE_BULLET_COUNTER_MAX = 16
# 双发子弹距离飞机中间位置偏移量
DOUBLE_BULLET_OFFSET = 30

# 分数
SCORE_SMALL_ENEMY = 10
SCORE_MID_ENEMY = 50
SCORE_BIG_ENEMY = 100

# 小型敌机每次移动时的偏移量
SMALL_ENEMY_OFFSET = 6
# 中型敌机每次移动时的偏移量
MID_ENEMY_OFFSET = 5
# 大型敌机每次移动时的偏移量
BIG_ENEMY_OFFSET = 2
# 子弹补给每次移动时的偏移量
BULLET_SUPPLY_OFFSET = 5
# 炸弹补给每次移动时的偏移量
BOMB_SUPPLY_OFFSET = 5
